//
// Generated file, do not edit! Created by nedtool 5.4 from broadcastMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __BROADCASTMESSAGE_M_H
#define __BROADCASTMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>broadcastMessage.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message BroadcastMessage
 * {
 *     int hopCount;
 * }
 * </pre>
 */
class BroadcastMessage : public ::omnetpp::cMessage
{
  protected:
    int hopCount = 0;

  private:
    void copy(const BroadcastMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BroadcastMessage&);

  public:
    BroadcastMessage(const char *name=nullptr, short kind=0);
    BroadcastMessage(const BroadcastMessage& other);
    virtual ~BroadcastMessage();
    BroadcastMessage& operator=(const BroadcastMessage& other);
    virtual BroadcastMessage *dup() const override {return new BroadcastMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BroadcastMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BroadcastMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BROADCASTMESSAGE_M_H

